"""start and end date for workout plan

Revision ID: 014ea1610b3c
Revises: 1f8a63297cd3
Create Date: 2025-04-28 23:37:17.367623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014ea1610b3c'
down_revision: Union[str, None] = '1f8a63297cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plan', sa.Column('week_start_date', sa.Date(), nullable=False))
    op.add_column('workout_plan', sa.Column('week_end_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plan', 'week_end_date')
    op.drop_column('workout_plan', 'week_start_date')
    # ### end Alembic commands ###
