"""blitz question remove fields

Revision ID: 0333a7c9b34c
Revises: 686d49d4dc08
Create Date: 2025-05-02 13:15:30.635517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0333a7c9b34c'
down_revision: Union[str, None] = '686d49d4dc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blitz_questions', 'gems_earned')
    op.drop_column('blitz_questions', 'expirience_earned')
    op.drop_column('blitz_questions', 'is_correct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blitz_questions', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('blitz_questions', sa.Column('expirience_earned', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blitz_questions', sa.Column('gems_earned', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
