"""calories fields

Revision ID: 06c37692f6b6
Revises: 6e55932cdf31
Create Date: 2025-05-11 10:25:10.558555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c37692f6b6'
down_revision: Union[str, None] = '6e55932cdf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('intensity', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('kg50_calories', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('kg60_calories', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('kg70_calories', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('kg80_calories', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('kg90_calories', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('kg100_calories', sa.Float(), nullable=True))
    op.add_column('planned_exercises', sa.Column('calories', sa.Float(), nullable=False))
    op.add_column('random_exercises', sa.Column('calories', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('calories_burned_daily', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('calories_eaten_daily', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('proteins_eaten_daily', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('fats_eaten_daily', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('carbs_eaten_daily', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'carbs_eaten_daily')
    op.drop_column('users', 'fats_eaten_daily')
    op.drop_column('users', 'proteins_eaten_daily')
    op.drop_column('users', 'calories_eaten_daily')
    op.drop_column('users', 'calories_burned_daily')
    op.drop_column('random_exercises', 'calories')
    op.drop_column('planned_exercises', 'calories')
    op.drop_column('exercises', 'kg100_calories')
    op.drop_column('exercises', 'kg90_calories')
    op.drop_column('exercises', 'kg80_calories')
    op.drop_column('exercises', 'kg70_calories')
    op.drop_column('exercises', 'kg60_calories')
    op.drop_column('exercises', 'kg50_calories')
    op.drop_column('exercises', 'intensity')
    # ### end Alembic commands ###
