"""is eaten field for meal

Revision ID: 1f8a63297cd3
Revises: 8bb738824581
Create Date: 2025-04-28 21:24:15.878224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8a63297cd3'
down_revision: Union[str, None] = '8bb738824581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('is_eaten', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'is_eaten')
    # ### end Alembic commands ###
