"""image for muscle group

Revision ID: 285ab85f6b9a
Revises: c2b143ef882d
Create Date: 2025-04-18 23:43:56.008214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285ab85f6b9a'
down_revision: Union[str, None] = 'c2b143ef882d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muscle_groups', sa.Column('image', sa.String(), nullable=True))
    op.add_column('workout_days', sa.Column('muscle_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workout_days', 'muscle_groups', ['muscle_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_days', type_='foreignkey')
    op.drop_column('workout_days', 'muscle_group_id')
    op.drop_column('muscle_groups', 'image')
    # ### end Alembic commands ###
