"""overlaps

Revision ID: 578ef1b76b80
Revises: b6e0d9512003
Create Date: 2025-04-27 10:45:47.835228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578ef1b76b80'
down_revision: Union[str, None] = 'b6e0d9512003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_restriction', sa.Column('dish_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_restriction', 'dishes', ['dish_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_restriction', type_='foreignkey')
    op.drop_column('user_restriction', 'dish_id')
    # ### end Alembic commands ###
