"""blitz question fields

Revision ID: 686d49d4dc08
Revises: cf5567c3780c
Create Date: 2025-05-02 13:06:49.012978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686d49d4dc08'
down_revision: Union[str, None] = 'cf5567c3780c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blitz_questions', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.add_column('blitz_questions', sa.Column('gems_earned', sa.Integer(), nullable=True))
    op.add_column('blitz_questions', sa.Column('expirience_earned', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blitz_questions', 'expirience_earned')
    op.drop_column('blitz_questions', 'gems_earned')
    op.drop_column('blitz_questions', 'is_correct')
    # ### end Alembic commands ###
