"""is completed field for workout day

Revision ID: 802478ee55b4
Revises: 82aea1e81f4d
Create Date: 2025-04-29 18:58:36.843281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802478ee55b4'
down_revision: Union[str, None] = '82aea1e81f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_days', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_days', 'is_completed')
    # ### end Alembic commands ###
