"""workout day and planned exercises statuses

Revision ID: 82aea1e81f4d
Revises: 014ea1610b3c
Create Date: 2025-04-29 00:17:58.016213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82aea1e81f4d'
down_revision: Union[str, None] = '014ea1610b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_exercises', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('workout_days', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_days', 'is_active')
    op.drop_column('planned_exercises', 'is_active')
    # ### end Alembic commands ###
