"""training place enum (2)

Revision ID: 8399dd78b28f
Revises: 89107f18c05f
Create Date: 2025-05-29 01:58:58.038343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8399dd78b28f'
down_revision: Union[str, None] = '89107f18c05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE trainingplaceenum ADD VALUE IF NOT EXISTS 'gym'")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
