"""proteins fats and carbs in meal

Revision ID: 8bb738824581
Revises: c71c188ea5ee
Create Date: 2025-04-27 16:23:00.161653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb738824581'
down_revision: Union[str, None] = 'c71c188ea5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('proteins', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('fats', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('carbs', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'carbs')
    op.drop_column('meals', 'fats')
    op.drop_column('meals', 'proteins')
    # ### end Alembic commands ###
