"""dish restriction

Revision ID: a64c7e8c5290
Revises: 9ea0213ae5ac
Create Date: 2025-05-22 20:03:45.416296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64c7e8c5290'
down_revision: Union[str, None] = '9ea0213ae5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_restriction',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('restriction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['restriction_id'], ['restrictions.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'restriction_id')
    )
    op.drop_constraint('user_restriction_dish_id_fkey', 'user_restriction', type_='foreignkey')
    op.drop_column('user_restriction', 'dish_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_restriction', sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_restriction_dish_id_fkey', 'user_restriction', 'dishes', ['dish_id'], ['id'])
    op.drop_table('dish_restriction')
    # ### end Alembic commands ###
