"""field for blitz polls

Revision ID: af9bff0a35ba
Revises: 0333a7c9b34c
Create Date: 2025-05-02 13:29:34.743273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9bff0a35ba'
down_revision: Union[str, None] = '0333a7c9b34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blitz_polls', sa.Column('expirience_earned', sa.Integer(), nullable=False))
    op.add_column('blitz_polls', sa.Column('gems_earned', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blitz_polls', 'gems_earned')
    op.drop_column('blitz_polls', 'expirience_earned')
    # ### end Alembic commands ###
