"""random exercises

Revision ID: d8641a2dba69
Revises: d42e98f78bee
Create Date: 2025-04-22 17:01:47.062689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8641a2dba69'
down_revision: Union[str, None] = 'd42e98f78bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sets_number', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('expirience', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_random_exercises_id'), 'random_exercises', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_random_exercises_id'), table_name='random_exercises')
    op.drop_table('random_exercises')
    # ### end Alembic commands ###
