"""expirience and gems default values in exercise

Revision ID: f0fe8c35db83
Revises: 5f1c44a5022b
Create Date: 2025-04-14 17:37:44.848270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fe8c35db83'
down_revision: Union[str, None] = '5f1c44a5022b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('expirience_default', sa.Integer(), nullable=False))
    op.add_column('exercises', sa.Column('expirience_level', sa.String(), nullable=False))
    op.drop_column('exercises', 'expirience_level_default')
    op.add_column('planned_exercises', sa.Column('expirience', sa.Integer(), nullable=False))
    op.drop_column('planned_exercises', 'expirience_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_exercises', sa.Column('expirience_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('planned_exercises', 'expirience')
    op.add_column('exercises', sa.Column('expirience_level_default', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('exercises', 'expirience_level')
    op.drop_column('exercises', 'expirience_default')
    # ### end Alembic commands ###
